import type { FormTemplate } from "@/types";
import {
  StarRatingForm,
  NPSForm,
  ContactForm,
  QuickPollForm,
  ProductFeedbackForm,
  SurveyForm,
  SupportTicketForm,
  EventFeedbackForm,
} from "@/components/templates";

export const formTemplates: FormTemplate[] = [
  {
    id: "star-rating",
    name: "Star Rating",
    description:
      "Traditional 5-star rating system for product or service evaluation",
    type: "rating",
    category: "customer-satisfaction",
    preview: StarRatingForm,
    height: 320,
    width: "small",
    tags: ["stars", "rating", "evaluation"],
    popular: true,
  },
  {
    id: "nps-survey",
    name: "NPS Survey",
    description:
      "Net Promoter Score survey to measure customer loyalty and satisfaction",
    type: "nps",
    category: "customer-satisfaction",
    preview: NPSForm,
    height: 380,
    width: "large",
    tags: ["nps", "loyalty", "recommendation"],
    popular: true,
  },
  {
    id: "contact-form",
    name: "Contact Form",
    description: "Simple contact form for inquiries and support requests",
    type: "contact",
    category: "support",
    preview: ContactForm,
    height: 480,
    width: "medium",
    tags: ["contact", "support", "inquiry"],
  },
  {
    id: "quick-poll",
    name: "Quick Poll",
    description: "Single question poll for quick decision making and opinions",
    type: "survey",
    category: "research",
    preview: QuickPollForm,
    height: 280,
    width: "small",
    tags: ["poll", "quick", "opinion"],
  },
  {
    id: "product-feedback",
    name: "Product Feedback",
    description:
      "Comprehensive feedback form for product improvements and features",
    type: "feedback",
    category: "product",
    preview: ProductFeedbackForm,
    height: 520,
    width: "large",
    tags: ["product", "improvement", "features"],
  },
  {
    id: "survey-form",
    name: "Multi-Question Survey",
    description: "Detailed survey with multiple questions and response types",
    type: "survey",
    category: "research",
    preview: SurveyForm,
    height: 600,
    width: "large",
    tags: ["survey", "research", "detailed"],
  },
  {
    id: "event-feedback",
    name: "Event Feedback",
    description: "Collect feedback from event attendees about their experience",
    type: "feedback",
    category: "feedback",
    preview: EventFeedbackForm,
    height: 450,
    width: "medium",
    tags: ["event", "feedback", "experience"],
  },
  {
    id: "support-ticket",
    name: "Support Ticket",
    description: "Help desk form for technical support and issue reporting",
    type: "contact",
    category: "support",
    preview: SupportTicketForm,
    height: 520,
    width: "medium",
    tags: ["support", "ticket", "help"],
  },
];
